---
# php_ppa_repos
# - repo: "ondrej/php"                           #required
#   state: present                               #default
#   update_cache: yes                            #default
#   validate_certs: yes                          #default
php_ppa_repos: []
# php_packages
# - name: "php7.0-curl"                          #required
#   state: present                               #default
php_packages:
- name: "php7.0-common"
- name: "php7.0-cli"
- name: "php7.0-fpm"
- name: "php7.0-bz2"
- name: "php7.0-curl"
- name: "php7.0-gd"
- name: "php7.0-gmp"
- name: "php7.0-intl"
- name: "php7.0-json"
- name: "php7.0-mbstring"
- name: "php7.0-mcrypt"
- name: "php7.0-mysql"
- name: "php7.0-opcache"
- name: "php7.0-pdo"
- name: "php7.0-pgsql"
- name: "php7.0-phar"
- name: "php7.0-readline"
- name: "php7.0-sqlite3"
- name: "php7.0-xml"
- name: "php7.0-zip"
php_cli_config_path: "/etc/php/7.0/cli/php.ini"
php_cli_short_open_tag: "Off"
php_cli_expose_php: "Off"
php_cli_max_execution_time: "0"
php_cli_max_input_time: "60"
php_cli_memory_limit: "512M"
php_cli_error_reporting: "E_ALL & ~E_DEPRECATED & ~E_STRICT"
php_cli_display_errors: "Off"
php_cli_display_startup_errors: "Off"
php_cli_track_errors: "Off"
php_cli_html_errors: "Off"
php_cli_variables_order: "GPCS"
php_cli_request_order: "GP"
php_cli_post_max_size: "8M"
php_cli_default_mimetype: "text/html"
php_cli_default_charset: "UTF-8"
php_cli_upload_max_filesize: "10M"
php_cli_max_file_uploads: "3"
php_cli_date_timezone: "UTC"
php_cli_include_path: ".:/usr/share/php"
php_cli_enable_includes: true
php_cli_assert_enable: "-1"
php_cli_assert_exception: "1"
php_cli_opcache_enable: "0"
php_cli_opcache_memory_consumption: "64"
php_cli_opcache_interned_strings_buffer: "16"
php_cli_opcache_max_accelerated_files: "4000"
php_cli_opcache_validate_timestamps: "1"
php_cli_opcache_revalidate_freq: "0"
php_cli_opcache_fast_shutdown: "1"
# php_cli_extra_settings
# - setting: "xdebug.max_nesting_level=250"      #required
#   state: present                               #default
php_cli_extra_settings: []
php_fpm_service: "php7.0-fpm"
php_fpm_config_path: "/etc/php/7.0/fpm/php.ini"
php_fpm_pool_path: "/etc/php/7.0/fpm/pool.d/www.conf"
php_fpm_user: "www-data"
php_fpm_group: "www-data"
php_fpm_listen: "127.0.0.1:9000"
php_fpm_short_open_tag: "Off"
php_fpm_expose_php: "Off"
php_fpm_max_execution_time: "30"
php_fpm_max_input_time: "60"
php_fpm_memory_limit: "512M"
php_fpm_error_reporting: "E_ALL & ~E_DEPRECATED & ~E_STRICT"
php_fpm_display_errors: "Off"
php_fpm_display_startup_errors: "Off"
php_fpm_track_errors: "Off"
php_fpm_html_errors: "On"
php_fpm_variables_order: "GPCS"
php_fpm_request_order: "GP"
php_fpm_post_max_size: "8M"
php_fpm_default_mimetype: "text/html"
php_fpm_default_charset: "UTF-8"
php_fpm_upload_max_filesize: "10M"
php_fpm_max_file_uploads: "3"
php_fpm_date_timezone: "UTC"
php_fpm_include_path: ".:/usr/share/php"
php_fpm_enable_includes: true
php_fpm_assert_enable: "-1"
php_fpm_assert_exception: "1"
php_fpm_opcache_enable: "1"
php_fpm_opcache_memory_consumption: "64"
php_fpm_opcache_interned_strings_buffer: "16"
php_fpm_opcache_max_accelerated_files: "4000"
php_fpm_opcache_validate_timestamps: "1"
php_fpm_opcache_revalidate_freq: "0"
php_fpm_opcache_fast_shutdown: "1"
# php_fpm_extra_settings
# - setting: "xdebug.max_nesting_level=250"      #required
#   state: present                               #default
php_fpm_extra_settings: []
